services:
  engine:
    image: eclipse-temurin:21-jre
    container_name: engine
    working_dir: /opt/app
    volumes:
      - ./app:/opt/app/app:ro         # engine-app.jar
      - ./config:/opt/app/config:ro   # engine.config
      - ./lib:/opt/app/lib:ro
    command: ["java","-jar","/opt/app/app/engine-app.jar"]
    ports:
      - "6100:6100"   # health TCP (lo usar√° el Monitor)
    stdin_open: true
    tty: true
