services:
  central:
    image: eclipse-temurin:25-jre
    container_name: central
    working_dir: /opt/app
    volumes:
      - ./app:/opt/app/app:ro        # central-app.jar aquí
      - ./config:/opt/app/config:ro  # central.config aquí
      - ./lib:/opt/app/lib:ro        # si usas libs externas
    command: ["java","-jar","/opt/app/app/central-app.jar"]
    ports:
      - "5000:5000"   # socket Monitor/Driver
      - "8080:8080"   # panel HTTP
    stdin_open: true
    tty: true
